### ISSUE TITLE
Automatically bump JupyterHub's version of pangeo/base-notebook

### ISSUE THREAD

**Issue by TomAugspurger** [dask/helm-chart#103]
The daskhub helm chart requires dask-gateway and jupyterhub. These are provided in the pangeo/base-notebook docker image.

Right now the version is pinned. We should either unpin it, or add a Github Action to update it based on releases of pangeo/base-notebook.

**Comment by consideRatio** [comment]
Ah this refers to...

https://github.com/dask/helm-chart/blob/d3aed9390393627149fd0315f54f3d97aeabb198/daskhub/values.yaml#L53-L56

Yeah, hmmm, I'd say having it automatically get bumped as new images arrive is what makes sense. Once the chart is installed, you don't want the image to drift.
