### ISSUE TITLE
The example documentation on Matching the User Environment on this article is not right

### ISSUE THREAD

**Issue by rezuma** [dask/helm-chart#104]
**What happened**:
The example documentation on Matching the User Environment on this article is not right
https://docs.dask.org/en/latest/setup/kubernetes-helm.html#matching-the-user-environment

 I have deployed twice and generates this error:
**ValueError: Unknown fields ['image']**

**What you expected to happen**:
The whole  extraConfig:     optionHandler: | should go inside a parent level called gateway like it correctly shows on the example prior to this on file: secrets.yaml

**Comment by jacobtomlinson** [comment]
Thanks for raising this @rezuma.

The docs you are referring to live in the main dask/dask repo.

https://github.com/dask/dask/blob/master/docs/source/setup/kubernetes-helm.rst

Do you feel you coudl raise a PR to make the corrections you have noted?

**Comment by rezuma** [comment]
Thanks for making the change. I didnt read your respond in time to raise the PR. Amazing work you are all doing.
