### ISSUE TITLE
JupyterHub Helm chart dependency bump to 0.10.0-beta.1 or 0.10.0 in not too long

### ISSUE THREAD

**Issue by consideRatio** [dask/helm-chart#116]
JupyterHub Helm chart 0.10.0-beta.1 is now released, with a [Changelog](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/CHANGELOG.md). I think bumping to that will help @tjcrone for example in https://github.com/jupyterhub/kubespawner/issues/282#issuecomment-716501852 by getting a more recent version of KubeSpawner.

**Comment by TomAugspurger** [comment]
How would you recommend rolling this out? Should we have a `daskhub` beta release that just bumps the jupyterhub version? Or is it probably OK to just depend on the beta jupyterhub release?

**Comment by consideRatio** [comment]
@TomAugspurger I'm not sure how to manage versions of DaskHub with a dependency on two different Helm charts that play a big role in its functionality =/ I think it could make sense to have development releases in between validated "this all seem to work" releases though.

**Comment by consideRatio** [comment]
Closed by #120! Thanks @GeorgianaElena!!
