### ISSUE TITLE
Adding volumes

### ISSUE THREAD

**Issue by lukejpreston** [dask/helm-chart#12]
Is it possible to add volumes to the workers? I need them to access files and I have been doing it using volumes with docker compose, now I am using helm and this is the only thing which is missing.

That being said, if there is another way to solve the problem:

Using dask to calculate checksums in parallel. Without using `client.upload_file` could I do this without a volume?

**Comment by jacobtomlinson** [comment]
We've just migrated the chart back here from helm/stable and I'm just reviewing old issues. Sorry we didn't get back to you at the time.

I'm going to close this issue out for now but if you still have a requirement for this then feel free to comment and we can reopen it.
