### ISSUE TITLE
Suggestion: "chart: dask" and "chart: daskhub" label for issues/PRs

### ISSUE THREAD

**Issue by consideRatio** [dask/helm-chart#124]
Since there are two helm charts and one repo with issues associated with one or the either, it would be nice to have a label to use in issues / prs to separate these from each other.

When I visit this repo to consider existing issues etc for one of the helm charts, it would help me a bit.

**Comment by jacobtomlinson** [comment]
Good idea! I've added these.

![image](https://user-images.githubusercontent.com/1610850/98379722-82895980-203f-11eb-8c48-0b37d647b30e.png)

**Comment by consideRatio** [comment]
@jacobtomlinson perhaps i can be granted triaging rights in this repo?

**Comment by jacobtomlinson** [comment]
We've gone one further and given you write access. Thanks for your help here!
