### ISSUE TITLE
How to specify static IP Address for Scheduler in Helm Chart?

### ISSUE THREAD

**Issue by rileyhun** [dask/helm-chart#136]
Hi - I was wondering if there is a place in the yaml file where we can specify the static IP address that I've reserved for the external load balancer of the Dask Cluster scheduler? 

Thanks in advance. 

Riley

**Comment by rileyhun** [comment]
Thanks so much @jacobtomlinson!

**Comment by jacobtomlinson** [comment]
Sure thing! This will be in `4.5.5`.
