### ISSUE TITLE
[daskhub] defaults deployment failing with the latest version

### ISSUE THREAD

**Issue by TomAugspurger** [dask/helm-chart#142]
With the latest version of daskhub, I'm unable to connect to the dask-gateway API server. Anything that interacts with it `gateway.list_clusters()` hangs and then raises with `ServerDisconnectedError: Server disconnected`)
```
#kubectl create namespace dhub
helm upgrade --wait --install --render-subchart-notes \
        dhub dask/daskhub \
        --namespace dhub \
        --values config.yaml \
        --values secrets.yaml
``` 

Looking at the logs for the pods

**dask-gateway-api**
```
e$ kubectl -n dhub logs -f api-dhub-dask-gateway-566f7d64f5-45xf5
[I 2020-11-17 18:33:23.369 DaskGateway] Starting dask-gateway-server - version 0.9.0
[I 2020-11-17 18:33:23.796 DaskGateway] Authenticator: 'dask_gateway_server.auth.JupyterHubAuthenticator'
[I 2020-11-17 18:33:23.797 DaskGateway] Backend: 'dask_gateway_server.backends.kubernetes.backend.KubeBackend'
[I 2020-11-17 18:33:23.873 DaskGateway] Dask-Gateway server started
[I 2020-11-17 18:33:23.873 DaskGateway] - Private API server listening at http://:8000
[W 2020-11-17 18:34:05.002 DaskGateway] 404 GET / 0.796ms
[W 2020-11-17 18:45:45.636 DaskGateway] 401 GET /api/v1/clusters/ 0.529ms
```

**hub**

```
Setting DASK_GATEWAY__ADDRESS http://proxy-public/services/dask-gateway
Adding dask-gateway service URL
[I 2020-11-17 18:33:59.470 JupyterHub app:2332] Running JupyterHub version 1.2.1
[I 2020-11-17 18:33:59.470 JupyterHub app:2362] Using Authenticator: dummyauthenticator.dummyauthenticator.DummyAuthenticator
[I 2020-11-17 18:33:59.470 JupyterHub app:2362] Using Spawner: kubespawner.spawner.KubeSpawner-0.14.1
[I 2020-11-17 18:33:59.470 JupyterHub app:2362] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-1.2.1
[I 2020-11-17 18:33:59.471 JupyterHub app:1457] Writing cookie_secret to /srv/jupyterhub/jupyterhub_cookie_secret
[I 2020-11-17 18:33:59.485 alembic.runtime.migration migration:155] Context impl SQLiteImpl.
[I 2020-11-17 18:33:59.485 alembic.runtime.migration migration:158] Will assume non-transactional DDL.
[I 2020-11-17 18:33:59.509 alembic.runtime.migration migration:517] Running stamp_revision  -> 4dc2d5a8c53c
[I 2020-11-17 18:33:59.530 alembic.runtime.migration migration:155] Context impl SQLiteImpl.
[I 2020-11-17 18:33:59.530 alembic.runtime.migration migration:158] Will assume non-transactional DDL.
[W 2020-11-17 18:33:59.766 JupyterHub auth:153] DummyAuthenticator.whitelist is deprecated in JupyterHub 1.2, use DummyAuthenticator.allowed_users instead
[I 2020-11-17 18:33:59.903 JupyterHub app:1840] Adding API token for service: dask-gateway
[I 2020-11-17 18:33:59.938 JupyterHub app:2399] Initialized 0 spawners in 0.003 seconds
[I 2020-11-17 18:33:59.940 JupyterHub app:2611] Not starting proxy
[W 2020-11-17 18:34:04.947 JupyterHub proxy:785] api_request to the proxy failed with status code 599, retrying...
[I 2020-11-17 18:34:04.985 JupyterHub app:2647] Hub API listening on http://:8081/hub/
[I 2020-11-17 18:34:04.985 JupyterHub app:2649] Private Hub API connect url http://hub:8081/hub/
[I 2020-11-17 18:34:04.985 JupyterHub app:2662] Starting managed service cull-idle
[I 2020-11-17 18:34:04.985 JupyterHub service:339] Starting service 'cull-idle': ['python3', '-m', 'jupyterhub_idle_culler', '--url=http://localhost:8081/hub/api', '--timeout=3600', '--cull-every=600', '--concurrency=10']
[I 2020-11-17 18:34:04.987 JupyterHub service:121] Spawning python3 -m jupyterhub_idle_culler --url=http://localhost:8081/hub/api --timeout=3600 --cull-every=600 --concurrency=10
[I 2020-11-17 18:34:04.991 JupyterHub app:2671] Adding external service dask-gateway at http://traefik-dhub-dask-gateway.dhub
[I 2020-11-17 18:34:05.005 JupyterHub proxy:320] Checking routes
[I 2020-11-17 18:34:05.006 JupyterHub proxy:400] Adding default route for Hub: / => http://hub:8081
[W 2020-11-17 18:34:05.007 JupyterHub proxy:373] Adding missing route for dask-gateway (Server(url=http://traefik-dhub-dask-gateway.dhub:80/services/dask-gateway/, bind_url=http://traefik-dhub-dask-gateway.dhub:80/services/dask-gateway/))
[I 2020-11-17 18:34:05.009 JupyterHub proxy:239] Adding service dask-gateway to proxy /services/dask-gateway/ => http://traefik-dhub-dask-gateway.dhub:80
[I 2020-11-17 18:34:05.017 JupyterHub app:2722] JupyterHub is now running at http://:8000
[I 2020-11-17 18:34:05.156 JupyterHub log:181] 200 GET /hub/api/users (cull-idle@127.0.0.1) 43.97ms
[I 2020-11-17 18:35:10.035 JupyterHub proxy:320] Checking routes
[I 2020-11-17 18:36:05.027 JupyterHub proxy:320] Checking routes
[I 2020-11-17 18:37:05.028 JupyterHub proxy:320] Checking routes
[I 2020-11-17 18:38:05.028 JupyterHub proxy:320] Checking routes
[I 2020-11-17 18:39:05.027 JupyterHub proxy:320] Checking routes
[I 2020-11-17 18:40:05.027 JupyterHub proxy:320] Checking routes
[W 2020-11-17 18:41:10.030 JupyterHub proxy:785] api_request to the proxy failed with status code 599, retrying...
[I 2020-11-17 18:41:10.081 JupyterHub proxy:320] Checking routes
[I 2020-11-17 18:42:05.026 JupyterHub proxy:320] Checking routes
[I 2020-11-17 18:43:05.028 JupyterHub proxy:320] Checking routes
```

I'll look into what's going on.

**Comment by TomAugspurger** [comment]
Pretty strange. I'm trying to mimic the auth flow manually.

```python
import requests
from dask_gateway.auth import JupyterHubAuth

url = "http://api-dhub-staging-dask-gateway:8000"

r = requests.get(f"{url}/api/version")
r.json()  # 200, no auth needed 

r = requests.get(f"{url}/api/v1/clusters/")
r.json()  #  401, Authentication requred

headers, _ = auth.pre_request(r)

r2 = requests.get(f"{url}/api/v1/clusters/", headers=headers)
r2.json()
```

In the logs the first couple lines are expected. A 200 for the version check, a 401 for the unauthenticated request. Then things get strange... 

```
[I 2020-11-19 14:57:05.597 DaskGateway] 200 GET /api/version 5.529ms
[W 2020-11-19 14:57:49.609 DaskGateway] 401 GET /api/v1/clusters/ 0.512ms
[E 2020-11-19 15:00:14.609 aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 971, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('10.0.234.121', 8081)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/dask_gateway_server/routes.py", line 13, in inner
    return await handler(request)
  File "/usr/local/lib/python3.8/site-packages/dask_gateway_server/routes.py", line 47, in inner
    return await auth.authenticate_and_handle(request, handler)
  File "/usr/local/lib/python3.8/site-packages/dask_gateway_server/auth.py", line 95, in authenticate_and_handle
    user = await self.authenticate(request)
  File "/usr/local/lib/python3.8/site-packages/dask_gateway_server/auth.py", line 389, in authenticate
    resp = await self.session.get(url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 527, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 537, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 894, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1053, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1022, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 977, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 10.0.234.121:8081 ssl:default [Connect call failed ('10.0.234.121', 8081)]
[E 2020-11-19 15:00:14.617 DaskGateway] 500 GET /api/v1/clusters/ 130714.216ms
```


Chasing down GitHub issues, I see https://github.com/aio-libs/aiohttp/issues/5155 which has the same error message. That mentions 0.0.0.0 vs. 127.0.0.1. I also see https://github.com/dask/dask-gateway/issues/348 about `host`, but the error message and issues there is different.

I don't see an easy way to specify host at https://github.com/dask/dask-gateway/blob/master/dask-gateway-server/dask_gateway_server/backends/kubernetes/controller.py#L1028-L1029. Dunno if there's an easy way to test this (maybe @jcrist has an idea). The hard way would be to build a docker image that has the changes and specify that.

**Comment by TomAugspurger** [comment]
Worth noting: I just did the stock deployment onto GCP and things work just fine. My failing deployment is on Azure's AKS (though it's strange that things would work fine on AKS with the older daskhub release).

**Comment by consideRatio** [comment]
Hmm... Perhaps disable all network policies in the z2jh deployment? hub.networkPolicy.enabled=false and the same for proxy.chp. and proxy.traefik. and singleuser.

Ive seen network policy controller misbehave in a k3s based cluster for example.

**Comment by consideRatio** [comment]
It is really complicated that this is upgrading both z2jh and daskgateway in the same bump :/, it is right? It would be soo good if this could isolate one upgrade

**Comment by consideRatio** [comment]
There seem to be issues speaking between the hub and proxy, why? It could be caused by networkpolicies or that we use DNS names rather than IPs now. Try disabling network policies is a first step to take.

**Comment by TomAugspurger** [comment]
Yeah, bumping both dask-gateway and jupyterhub in the same release may have been a mistake :)

But your suggestion to look into network policies was fantastic. With those disabled

```yaml
jupyterhub:
  hub:
    networkPolicy:
      enabled: False
  proxy:
    chp:
      networkPolicy:
        enabled: False
  singleuser:
    networkPolicy:
      enabled: False
```

And I've confirmed that I'm able to talk to the dask gateway API server.

Just to confirm, the line that lead you to networkPolicy is:

```
[W 2020-11-17 18:34:04.947 JupyterHub proxy:785] api_request to the proxy failed with status code 599, retrying...
```

Interestingly, I still see that warning after disabling the network polices. Perhaps it's not related.

**Comment by consideRatio** [comment]
> [W 2020-11-17 18:34:04.947 JupyterHub proxy:785] api_request to the proxy failed with status code 599, retrying...

As long as it doesn't fail in the long run, this is fine. It can show if the hub pod starts up faster than the proxy pod for example.

@TomAugspurger can you identify exactly what pod-to-pod communication that failed, and with what ports where involved in that communication?

> With the latest version of daskhub, I'm unable to connect to the dask-gateway API server. Anything that interacts with it gateway.list_clusters() hangs and then raises with ServerDisconnectedError: Server disconnected)

dask-gateway API server is a pod you try to reach, but from where? Is dask-gateway configured to speak with the hub pod or user pods directly without going through proxy-public? Then that is the issue from the perspective of the network policies. Any pod that tries to reach the hub directly, or reach the user pods directly, need to be granted access.

Btw, the network policies only regards connections being established.

**Comment by consideRatio** [comment]
```
        # Use JupyterHub to authenticate with Dask Gateway.
        c.KubeSpawner.environment.setdefault("DASK_GATEWAY__AUTH__TYPE", "jupyterhub")
```

I suspect this may cause. Yes, confirmed from [here](https://github.com/dask/dask-gateway/blob/09526b1de9308cb6bc61351d1562db8ca14e78f8/resources/helm/dask-gateway/templates/gateway/configmap.yaml#L92-L103). This is not allowed unless the pod has a label on it as well.

**Comment by TomAugspurger** [comment]
Thanks @consideRatio, you nailed it! Setting `hub.jupyter.org/network-access-hub: "true"` on the dask-gateway api pod did the trick.

I'll delete the deployment and try with that config value set. ~Then I'll figure out what to update in the chart~ nope, you beat me to it :)

**Comment by consideRatio** [comment]
Thank you @TomAugspurger !

**Comment by TomAugspurger** [comment]
I don't see an easy way to configure this from daskhub or a user's configuration. IIUC, none of the `*.common_labels` are included in the labels at https://github.com/dask/dask-gateway/blob/c2583548df19359d24031e1dd9161c616d3bed50/resources/helm/dask-gateway/templates/gateway/deployment.yaml#L6, which is just https://github.com/dask/dask-gateway/blob/09526b1de9308cb6bc61351d1562db8ca14e78f8/resources/helm/dask-gateway/templates/_helpers.tpl#L37-L46.

So I think we'll need Erik's pull request.

In the meantime, I think we just document that it's incompatible with JupyterHub 0.10's network policies. We can provide guidance on disabling them. Or if we don't want to do that (since they're presumably on for a reason), perhaps people will find their way to this issue and see https://github.com/dask/helm-chart/issues/142#issuecomment-730633411.

**Comment by consideRatio** [comment]
> In the meantime, I think we just document that it's incompatible with JupyterHub 0.10's network policies. We can provide guidance on disabling them.

Only `--set hub.networkPolicy.enabled=false` is needed at the moment I think

**Comment by TomAugspurger** [comment]
Correct, I just confirmed that. I will update the post.

**Comment by TomAugspurger** [comment]
I believe this has been addressed upstream in dask-gateway.
