### ISSUE TITLE
Release new daskhub version

### ISSUE THREAD

**Issue by consideRatio** [dask/helm-chart#149]
I've bumped the JupyterHub Helm chart dependency from 0.10.2 to 0.10.5 which includes some bugfixes from oauthenticator and jupyterhub.

I would assume we may bump the patch version for that then, but I think if we make a release for both the dask chart and daskhub chart, we should transition to a calendar versioning scheme instead or decouple the charts from each other.

**Comment by jacobtomlinson** [comment]
> we should transition to a calendar versioning scheme instead or decouple the charts from each other

Agreed. 

I raised this at the Dask maintainer meeting this week and it was decided that dask and distributed should go first with the switch to CalVer, then other subprojects can follow. This will happen in the next few weeks/months.

So for now we should continue with the coupled semver, even though it isn't a great thing to do.

**Comment by consideRatio** [comment]
@jacobtomlinson got it! Okay for me to cut a release bumping patch version in order to get daskhub bumped with jupyterhub's patch version bump?

**Comment by jacobtomlinson** [comment]
Please do!

**Comment by consideRatio** [comment]
4.5.6 was released the same day this issue was opened, but I forgot to close this issue.
