### ISSUE TITLE
Revive Dask Helm ?

### ISSUE THREAD

**Issue by quasiben** [dask/helm-chart#15]
@beberg and I were chatting about reviving the helm-chat repo here rather than rely on the official helm repo.  Currently there is a lingering PR to update the dask helm chart but it's not getting much attention from helm devs to merge in : https://github.com/helm/charts/pull/12552

It's also worth noting that Jupyterhub maintains it's own helm chart:
https://github.com/jupyterhub/zero-to-jupyterhub-k8s

cc @jacobtomlinson @mrocklin

**Comment by mrocklin** [comment]
Jacob was mentioning that this is now what the helm maintainers prefer.
Apparently there is also a place where we can register external chart
repositories.  I'll let him chime in here.

**Comment by jacobtomlinson** [comment]
Yep totally agree we should do this. The maintainers of the official helm stable/incubator repository are encouraging people to move their charts out to their own repository and register them with https://hub.helm.sh.

I went through this exercise [with a personal side project ](https://github.com/opsdroid/helm-chart)a couple of months ago and it wasn’t too bad, we can reuse the [chartpress config](https://github.com/opsdroid/helm-chart/blob/master/chartpress.yaml) and [CI](https://github.com/opsdroid/helm-chart/blob/master/.travis.yml)/[CD](https://github.com/opsdroid/helm-chart/blob/master/ci/deploy.sh) scripts from there if they are useful. The chart lives on the master branch and the deployment artifacts live on the gh-pages branch and therefore are served by GitHub. We then just need to PR into helm hub [like this](https://github.com/helm/hub/pull/99/files).

**Comment by mrocklin** [comment]
Thanks Jacob!
