### ISSUE TITLE
Clarify updated location of helm chart in repo description

### ISSUE THREAD

**Issue by skeller88** [dask/helm-chart#16]
It took me a bit to find that the helm chart is at https://github.com/helm/charts/tree/master/stable/dask. Can that be linked to in the description?

**Comment by jacobtomlinson** [comment]
Sorry you had trouble finding it.

We will actually be reviving this repo now that the helm charts repo is being replaced by https://hub.helm.sh/. See #15.

**Comment by skeller88** [comment]
Ok. So the helm chart link in the [dask kubernetes documentation](https://docs.dask.org/en/latest/setup/kubernetes-helm.html) should stay the same?

**Comment by jacobtomlinson** [comment]
It was previously correct, today it is not correct, but soon it will be correct again. Sorry for the confusion.

**Comment by skeller88** [comment]
No problem, thanks.
