### ISSUE TITLE
Coordinate JupyterHub and Dask Gateway deployments

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/helm-chart#166]
@choldgraf has raised jupyterhub/team-compass#382 to discuss how the community can better align efforts in deploying JupyterHub and other tools, including Dask. It mentions the `daskhub` chart in this repo as one implementation of this.

I've engaged with my thoughts from a Dask perspective but wanted to raise an issue here to increase visibility. 

If you're interested and have thoughts please go and engage over on that issue.

**Comment by consideRatio** [comment]
Closing as resolved at this point!
