### ISSUE TITLE
Allow for workers to connect to custom scheduler URL

### ISSUE THREAD

**Issue by andrii29** [dask/helm-chart#167]
hi!
It would be nice to allow for workers to connect to custom scheduler, but not the only one from this chart.
https://github.com/dask/helm-chart/blob/main/dask/templates/dask-worker-deployment.yaml#L43

```
          {{- if .Values.worker.customSchedulerURL }}
            - {{ .Values.worker.customSchedulerURL }}
          {{- else }}
             - {{ template "dask.fullname" . }}-scheduler:{{ .Values.scheduler.servicePort }}
          {{- end }}
```
Also would be nice to have ability to disable default scheduler deployment
```
scheduler:
  enabled: true
```

P.S. I already have dask cluster, and want to connect another set of wokers (with different cpu/mem config) to this cluster using same chart.

Regards,
Andrii

**Comment by jacobtomlinson** [comment]
Interesting use case, I hadn't considered this.

Would you be interested in submitting a PR to make this change?

**Comment by andrii29** [comment]
#169

**Comment by jacobtomlinson** [comment]
Thanks @andrii29

**Comment by andrii29** [comment]
Hello,
@jacobtomlinson 
is there a way to create new version of chart on helm repo with latest changes?
https://helm.dask.org/

**Comment by jacobtomlinson** [comment]
I just tagged a release, should be up on helm.dask.org shortly.

Note this is the first release since Dask generally switched to CalVer.

**Comment by andrii29** [comment]
hi,
@jacobtomlinson 
any updates on new chart release?
