### ISSUE TITLE
Allow to use daemonset instead of deployment in workers setup

### ISSUE THREAD

**Issue by andrii29** [dask/helm-chart#168]
Hello,
It would be nice to dynamically scale workers using nodeSelector labels, instead of changing **replicas** and redeploy.
This require only 2 changes
https://github.com/dask/helm-chart/blob/main/dask/templates/dask-worker-deployment.yaml#L2
https://github.com/dask/helm-chart/blob/main/dask/templates/dask-worker-deployment.yaml#L12
For example
(values)
```
worker:
  kind: Deployment|DaemonSet
```
(deploymentOrDaemonset)  
```
kind:  {{ .Values.worker.kind }}
spec:
 {{- if eq .Values.worker.kind "Deployment" }}
  replicas: {{ .Values.worker.replicaCount }}
 {{- end }} 
```

Regards,
Andrii

**Comment by jacobtomlinson** [comment]
Interesting I've never heard of folks scaling this way before.

I'm curious is your k8s cluster fixed size or scalable? Are you suggesting that you somehow label nodes in order to allow workers to be started on them?

**Comment by jacobtomlinson** [comment]
cc @yuvipanda, is this a pattern you've seen before?

**Comment by andrii29** [comment]
i have fixed size cluster. But some nodes are under load only half of a day. I want to use this nodes for additional dask workers for another half of day)
So, it would be more comfortable with daemonset and node labels update.
https://github.com/dask/helm-chart/blob/main/dask/values.yaml#L91

**Comment by consideRatio** [comment]
I have not seen this kind of pattern switching a deployment/daemonset.

I would suggest not doing it. If this feature is added, the next step would be to have a mix of deployment and daemonset which also could make sense.

I suggest that if this feature is added, it is done by adding a standalone daemonset with all the same properties that can be enabled or disabled, and would be disabled by default.

**Comment by andrii29** [comment]
ok, thanks for suggestions!
What do you thing about add another set of workers with different cpu/mem config?

**Comment by jacobtomlinson** [comment]
You should be able to do this now with the changes in #169
