### ISSUE TITLE
Disable Jupyter RBAK when jupyter is disabled

### ISSUE THREAD

**Issue by andrii29** [dask/helm-chart#170]
hi,
default values
https://github.com/dask/helm-chart/blob/main/dask/values.yaml#L101-L104
```
jupyter:
  name: jupyter
  enabled: true 
  rbac: true 
```
Even when i set `jupyter.enabled: false`, rbac will be created anyway, because of check only on `rbac: true`
https://github.com/dask/helm-chart/blob/main/dask/templates/dask-jupyter-serviceaccount.yaml#L1
Suggestion: change check to disable rbak resources when jupter disabled; or change defaults `jupyter.rbac: false`

`{{- if and .Values.jupyter.enabled .Values.jupyter.rbac  -}}`

Regards,
Andrii

**Comment by jacobtomlinson** [comment]
That sounds great. Could you raise a Pull Request?

**Comment by andrii29** [comment]
#171 #

**Comment by jacobtomlinson** [comment]
Thanks!
