### ISSUE TITLE
bugs in daskhub-2021.3.0 chart

### ISSUE THREAD

**Issue by bolliger32** [dask/helm-chart#172]
I've noticed a couple of (what I think are) bugs in the latest daskhub chart.

1. while it should point to v0.9.0 of the dask-gateway chart (as indicated in `Chart.yaml`, when you actually go inside the `charts/dask-gateway` folder it looks like it is v0.8.0.
2. It seems that all of the default values from the jupyterhub and dask-gateway dependencies are copied into the `values.yaml` file. I'm not sure if this is intentional or not, but it makes it hard to see what values are uniquely set for daskhub vs. just the defaults defined in the dependency charts.
3. When I deployed this version of the chart, my github auth seems to not work anymore. I'm guessing this is related to one of the above points, as I couldn't otherwise diagnose exactly why this would have happened.

I'm not actually sure how to determine how this chart gets deployed. I imagine it's somewhere within this repo, but couldn't easily locate it.

**Comment by jrbourbeau** [comment]
Also transferring this issue to ` dask/helm-chart` as that's the relevant location for the daskhub chart

**Comment by jacobtomlinson** [comment]
cc @TomAugspurger

**Comment by jacobtomlinson** [comment]
Thanks for raising this @bolliger32.

Are these same issues in `4.5.7` or is this a regression?

**Comment by bolliger32** [comment]
@jacobtomlinson it's a regression I believe

**Comment by jacobtomlinson** [comment]
`2021.3.1` is out now and hopefully shouldn't have the same issues.

Sorry about that!

**Comment by bolliger32** [comment]
thanks so much @jacobtomlinson !
