### ISSUE TITLE
Sorting is broken on helm.dask.org

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/helm-chart#176]
Since switching to CalVer the sorting is now broken as things are sotred alphabetically instead of numerically.

2021.3.1 should be at the top, but is coming in the middle between `2.2.1` and `3.0.0`.

https://github.com/dask/helm-chart/blob/gh-pages/index.md

**Comment by consideRatio** [comment]
It seems things are kind of weird, but there is a date now and the latest versions are sorted correctly based on the date. Should we close this as sufficiently resolved?

**Comment by consideRatio** [comment]
Going for a close given that this issue was opened before 6th april when I presume you or someone added the date sorting.
