### ISSUE TITLE
Add servicemonitor to chart

### ISSUE THREAD

**Issue by andrii29** [dask/helm-chart#181]
Hi,
it would be nice to have ability to enable servicemonitor for dask via this chart

Regards,
Andrii

**Comment by jacobtomlinson** [comment]
I assume you are referring to the prometheus monitoring operator and CRDs here.

This is slightly tricky as we currently do not use any CRDs in our chart, and not all users will have them installed. If you propose we add a template for the servicemonitor CRD could you point to some other charts that also do this so we can ensure we are doing it in a consistent and best practice way.

**Comment by andrii29** [comment]
Consider make it disabled by default
https://github.com/kubernetes/ingress-nginx/blob/master/charts/ingress-nginx/values.yaml#L523-L535
https://github.com/bitnami/charts/blob/master/bitnami/redis/values.yaml#L758-L769
https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/values.yaml#L184-L186

**Comment by jacobtomlinson** [comment]
Ok great! Sounds good to me.

Do you have any interesting in contributing this?

**Comment by andrii29** [comment]
sure, i'll try this.

**Comment by andrii29** [comment]
#182 #
