### ISSUE TITLE
Add support for additionalLabels in ServiceMonitor and PodMonitor

### ISSUE THREAD

**Issue by retrry** [dask/helm-chart#188]
Hello, 
would it be possible to add support for additional labels in ServiceMonitor and PodMonitor. We have prometheus configuration, which requires additional, specific label for it to be scraped (this is by design, so we would only collect info from where we want). 

There are other charts with additionalLabels support:
As an example: https://artifacthub.io/packages/helm/bitnami/postgresql (metrics.serviceMonitor.additionalLabels)

**Comment by jacobtomlinson** [comment]
Sure that would be fine. Do you have any interest in submitting a PR to add this?

**Comment by jacobtomlinson** [comment]
Closed in #191
