### ISSUE TITLE
Automated PRs are no longer triggering CI

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/helm-chart#216]
In the last couple of automated version bump PRs the CI has not been triggered and I've had to manually push an empty commit to get the checks to run.

**Comment by jacobtomlinson** [comment]
I've opened a [community question here](https://github.community/t/prs-created-by-actions-do-not-trigger-checks/210980).

**Comment by jacobtomlinson** [comment]
It looks like pushes made by the automation need tobe done with a Personal Access Token in order to trigger downstream workflows.

**Comment by consideRatio** [comment]
I think the made it so that bot triggered PRs opened with the $GITHUB_TPKEN credentials no longer trigger automation to run as a way to avoid endless loops of triggered workflows.
