### ISSUE TITLE
Upgrade to Jupyterhub 2.0.0

### ISSUE THREAD

**Issue by thomafred** [dask/helm-chart#218]
JupyterHub 2.0.0 was recently released, but DaskHub chart is still at version 1.2.0.

As JupyterHub 2.0.0 supports role-based access control, having this in DaskHub would be awesome :rocket:

**Comment by consideRatio** [comment]
This is an issue to be tracked in the JupyterHub Helm chart. A PR will be automatically opened to update the daskhub helm chart when a new release has been made of JupyterHub.

I'm thinking I can get a beta out early next week.
