### ISSUE TITLE
Compatibility with Kubernetes 1.22

### ISSUE THREAD

**Issue by guillaumeeb** [dask/helm-chart#227]
**What happened**:

When following some simplified instructions for deploying a daskhub I made a year ago and updated a few month ago (https://github.com/SupaeroDataScience/OBD/blob/master/notebooks/Kubernetes_Daskhub.ipynb), I encountered a problem when deploying the daskhub helm chart. So when launching `helm upgrade --wait --install`, I got:

```bash
Error: failed to install CRD crds/daskclusters.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
```

**What you expected to happen**:

No errors :).

**Minimal Complete Verifiable Example**:

https://github.com/SupaeroDataScience/OBD/blob/master/notebooks/Kubernetes_Daskhub.ipynb

**Anything else we need to know?**:

This is probably due to Kubernetes defaulting to 1.22 now, and also related to https://github.com/dask/helm-chart/issues/224.
Just specifying the previous Kubernetes version on GKE is a workaround:

```bash
gcloud container clusters create \
  ...
  --cluster-version 1.21 \
  dask-hub-k8s
```

The fix is probably easy, I'll try to see if I can find it!

**Comment by consideRatio** [comment]
daskhub depends on dask-gateway, and dask-gateway needs a new release where compatebility with k8s 1.22+ has been fixed. For now, you can't use daskhub on k8s 1.22 =/

This is the PR that resolved it upstream I think: https://github.com/dask/dask-gateway/pull/420

**Comment by guillaumeeb** [comment]
Thanks @consideRatio!

What is unfortunate is that I don't even use dask-gateway here. I'm only using dask-kubernetes. 

```yaml
dask-gateway:
  enabled: false
  gateway:
    auth:
      type: simple
      simple:
        password: "unused"

dask-kubernetes:
  enabled: true
```

But I guess the chart fron dasg-gateway is still parsed?

**Comment by consideRatio** [comment]
If you want daskhub, but not dask-gateway - what you want is the official jupyterhub helm chart - that is what remains.

If you want to have a dask cluster setup, you can also install the dask helm chart - which I think setups a standalone dask cluster. I think now though - this has become entirely off topic to the actual issue - which is still relevant to track by itself.

**Comment by guillaumeeb** [comment]
> If you want daskhub, but not dask-gateway - what you want is the official jupyterhub helm chart (z2jh.jupyter.org) - that is what remains.

I still use the dask-kubernetes part. The daskhub chart helps to create the correct RBAC configuration for Kubernetes here.

Back to the actual issue, this just needs a new official release of dask-gateway, and then a small PR and release here too?

**Comment by consideRatio** [comment]
> I still use the dask-kubernetes part. The daskhub chart helps to create the correct RBAC configuration for Kubernetes here.

Okay - I don't overview what that RBAC does at this point in time - I assume you are right that's relevant for you. Then, yes, a release of dask-gateway + a version bump in the dependency is whats needed.

**Comment by guillaumeeb** [comment]
This RBAC (https://github.com/dask/helm-chart/blob/main/daskhub/templates/dask-kubernetes-rbac.yaml) allows a notebook user to create dask clusters with dask-kubernetes. The need is explained here: https://kubernetes.dask.org/en/latest/kubecluster.html#role-based-access-control-rbac.

**Comment by consideRatio** [comment]
@guillaumeeb I see okay thanks! Wow that was a very big set of permissions granted to a user by default! They are not needed for anyone using dask-gateway.

**Comment by guillaumeeb** [comment]
Yup, I guess that is why dask-gateway is now considered the best practice and defaut for Pangeo like platforms.

Still, dask-kubernetes feels more natural to me, and I'm using the daskhub with students deploying their own platforms, so this is fine. I guess @jacobtomlinson would tell me there is a better option than daskhub (dask simple helm chart?), but I never had the time to play with other things, and the deployment of a Jupyterhub over Kubernetes is really interesting for students!

**Comment by guillaumeeb** [comment]
> and apply the RBAC template manually as a workaround.

A year ago, I wanted to do that. But I am so bad at Kubernetes, that it was way easier to use the daskhub chart that do it automatically. I still wanted to do it, and improve documentation in dask-kubernetes. But I never found the time to translate the 

> Create a service account you will use for Dask, and then attach the following Role to that ServiceAccount via a RoleBinding:

of https://kubernetes.dask.org/en/latest/kubecluster.html#role-based-access-control-rbac into real linux commands 😄.

**Comment by jacobtomlinson** [comment]
Helm can render out individual templates if you want to apply them manually. So you could apply just the RBAC like this

```
$ helm template -s \
        --namespace default \
        --set dask-kubernetes.enabled=true,dask-gateway.gateway.auth.jupyterhub.apiToken=abc123 \
        templates/dask-kubernetes-rbac.yaml \
        dask/daskhub | kubectl apply -f -
```

**Comment by consideRatio** [comment]
Version 2022.4.0 is released, closing this as resolved.
