### ISSUE TITLE
Daskhub `additional_worker_groups` configuration

### ISSUE THREAD

**Issue by BnJam** [dask/helm-chart#229]
The `additional_worker_groups: []` configuration for Dask-Kubernetes and in the Dask directory was recently included but it doesn't seem to have been included for Daskhub. 

Are we waiting on Dask-Gateway to catch up?

**Comment by jacobtomlinson** [comment]
Worker groups isn't currently supported in Dask Gateway (or anywhere else really).

**Comment by consideRatio** [comment]
Ah, I'll go for a close on this then as there is nothing to track in this github repo about this.
