### ISSUE TITLE
Remove generated files from version control

### ISSUE THREAD

**Issue by consideRatio** [dask/helm-chart#299]
Since we generate `.frigate` files into `README.md` files using `frigate`, we should not version control also the generated output, but instead generate it before a release of the Helm charts are made.

That way, we won't need automation to check if they are in sync, or automatically update the generated files if they are brought out of sync etc.

Note that whenever we ship the jupyterhub/zero-to-jupyterhub-k8s helm chart, we also generate files just in time in a similar way. We generate a `values.schema.json` file based on a `.yaml` file we maintain. So this pattern wouldn't be too new.

**Comment by jacobtomlinson** [comment]
I think most folks look at the `README` files in the `dask` and `daskhub` folders directly on GitHub rather than from inside a built release. I think removing them would be a bad experience.

**Comment by consideRatio** [comment]
I don't want a situation where either:
- we have failires in the CI system by default and manual work is required to fix it (current situation)
- documentation gets outdated and misleading
- we create a CI system that in itself is hard to develop/understand/maintain due to its complexity

> I think most folks look at the README files in the dask and daskhub folders directly on GitHub rather than from inside a built release. I think removing them would be a bad experience.

A compromise is to let the version controlled README.md point to for example https://artifacthub.io/packages/helm/dask/dask where it will be rendered and seen in full if we generate it from the `.frigate` template before packaging the Helm chart.

**Comment by consideRatio** [comment]
Wieee @jacobtomlinson that makes me happy!! I've opened #301 and #302 (which includes 301).

**Comment by consideRatio** [comment]
Resolved by #301 and #302.
