### ISSUE TITLE
is it possible to change the scheduler.service.name ?

### ISSUE THREAD

**Issue by webcoderz** [dask/helm-chart#323]
is it possible to change the service name having issues trying to connect my workers and other containers to the scheduler  using dask-scheduler:8786 ? the dask-scheduler:8786 value is hardcoded in another image container so trying to avoid changing that elsewhere

**Comment by webcoderz** [comment]
wrong repo.. but if you all know the answer for this and the dask operator.. would be cool!

**Comment by jacobtomlinson** [comment]
Closing in favour of https://github.com/dask/dask-kubernetes/issues/561
