### ISSUE TITLE
link to values.yaml not working on the front page README

### ISSUE THREAD

**Issue by raybellwaves** [dask/helm-chart#33]
When you scroll down to the README and click on any of the values.yaml files it brings up https://github.com/dask/helm-chart/blob/master/values.yaml. It works when clicking the links on https://github.com/dask/helm-chart/tree/master/dask

**Comment by jacobtomlinson** [comment]
The correct link should be https://github.com/dask/helm-chart/blob/master/dask/values.yaml.

Would you be interested in raising a PR to fix it?
