### ISSUE TITLE
Chart is using depracted `bokeh-port` argument

### ISSUE THREAD

**Issue by sushi30** [dask/helm-chart#338]
**Describe the issue**:

The chart is using the deprecated `bokeh-port` argument resulting in a broken deployments for versions after 2022.10.0.

**Comment by consideRatio** [comment]
I understand now that this issue relates to the dask Helm chart, and the following command line argument passed to `dask-scheduler`, which is [a CLI provided by dask/dsitrbuted](https://github.com/dask/distributed/blob/6afce9cce6ab402fa44736dc57b39fbc355b4c11/setup.py#L68).

https://github.com/dask/helm-chart/blob/0df23a0a20580b0de904565e2cfd926513744ca4/dask/templates/dask-scheduler-deployment.yaml#L38-L43

I could not see any breaking change notice in [dask/distributed's changelog](https://distributed.dask.org/en/stable/changelog.html) about this though. I figured out it relates to [this change](https://github.com/dask/distributed/pull/6735/files#diff-a3ae9b78713e342ba9660758c80c16ea06077924b14f4c1f08c8e982618f26aaL155-L166) and that the resolution is to change `--bokeh-port=<port>` to `--dashboard-address=:<port>`.

**Comment by consideRatio** [comment]
It appears also that the default is this, but I think we should keep it explicit still in this Helm chart for visibility.

```
  --dashboard-address TEXT      Address on which to listen for diagnostics
                                dashboard  [default: :8787]
```

**Comment by consideRatio** [comment]
The next release will have this resolved.

**Comment by ljstrnadiii** [comment]
Just ran into this. @consideRatio any idea when there will be another release here? Since we use helm for our dask clusters, I am struggling to test out new features in distributed==2022.10.2 such as https://github.com/dask/distributed/discussions/7128

**Comment by consideRatio** [comment]
@jacobtomlinson I'm not confident about the release process, is it to push a tag and thats it?

**Comment by consideRatio** [comment]
I investigated what has been done historically. I conclude:

1. Make a empty commit with message like this.
   ```
   git commit --allow-empty -m "Version 2022.11.0"
   ```
2. Tag the commit with an annotation and message like this.
   ```
   git tag -a 2022.11.0 -m "Version 2022.11.0"
   ```
3. Push the commit and tag
   ```
   git push --follow-tags --atomic
   ```

**Comment by ljstrnadiii** [comment]
Awesome. Thanks a ton @consideRatio!

**Comment by jacobtomlinson** [comment]
Yup, there is a utility script for this.

https://github.com/dask/helm-chart/blob/main/ci/release.sh
