### ISSUE TITLE
jupyterhub helm chart update 

### ISSUE THREAD

**Issue by merlos** [dask/helm-chart#420]
Whereas  in the file main [daskhub/Chart.yaml](https://github.com/dask/helm-chart/tree/main/daskhub)  the versions of jupiterhub and dask have been continuously updated using github actions to:
```
appVersion: "jh3.1.0-dg2023.9.0"
```
The latest version of the daskhub helm chart released in https://helm.dask.org/index.yaml is `2023.01.0` which correspondos to the app versions:
```
appVersion: jh2.0.0-dg2023.1.1
```

The Github Action that publishes the chart 
https://github.com/dask/helm-chart/blob/main/.github/workflows/publish-charts.yml 

Seems to expect a new tag in order to release the chart, but no new tags since jan 2023. 

Would it be possible for you to update the chart? 
In addition to releasing a new version, would it be possible to automate the release of the chart?

Thanks!

**Comment by jhamman** [comment]
Bumping this. @jacobtomlinson and @consideRatio - what is needed to push out a modern release of the daskhub chart?

**Comment by consideRatio** [comment]
I don't remember, but perhaps just push a git tag in this repo?
/ From mobile, i can have a look tomorrow

**Comment by consideRatio** [comment]
I pushed a 2024.1.0 tag, that did the trick - see https://helm.dask.org/
 
![image](https://github.com/dask/helm-chart/assets/3837114/038e7e9f-274b-4cc9-8380-cf2ac7835a4a)
