### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by dbalabka** [dask/helm-chart#432]
We utilise AWS Gravitrons heavily and are looking into starting to use Dask in EKS. However, it looks like Helm chart installs x86 version of the image, and the following error appears in the logs:
```
exec /usr/local/bin/kopf: exec format error
```

The Dask docker images can be built for ARM, but there is no official release yet:
https://github.com/dask/dask-docker/issues/128

Also, Coiled already supports ARM:
https://blog.coiled.io/blog/dask-graviton.html

I'm creating this ticket to help monitor the problem. However, it should be solved in [dask/dask-docker/issues/128](https://github.com/dask/dask-docker/issues/128)

**Comment by consideRatio** [comment]
There are two helm charts in this repo, one for a single dask cluster, and one for dask-gateway - which are you speaking about at the moment?

I think daskhub, which just is the jupyterhub helm chart + dask-gateway helm chart should handle arm64 --- if it doesn't, thats a bug to fix!

**Comment by dbalabka** [comment]
@consideRatio, thanks for the quick reply. To be precise:
```
helm install --repo https://helm.dask.org --generate-name dask-kubernetes-operator
```

**Comment by consideRatio** [comment]
Ah, I think that is an issue for https://github.com/dask/dask-kubernetes, as that chart is defined there. See https://github.com/dask/dask-kubernetes/blob/HEAD/dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/Chart.yaml.

**Comment by dbalabka** [comment]
@consideRatio , I'll get back to this issue when it becomes actual again. Apologies for non-quick reply.
