### ISSUE TITLE
Unable to install dask chart

### ISSUE THREAD

**Issue by ohashmi-cei** [dask/helm-chart#48]
Hi I keep getting the following error trying to install helm chart. I had a script and it was working fine until yesterday in GCP. it fails when I enter the following command:

helm install --name my-release dask/dask

Error: validation failed: [configmaps "my-release-dask-jupyter-config" not found, services "my-release-dask-jupyter" not found, services "my-release-dask-scheduler" not found, deployments.apps "my-release-dask-jupyter" not found, deployments.apps "my-release-dask-scheduler" not found, deployments.apps "my-release-dask-worker" not found]

**Comment by jacobtomlinson** [comment]
Have you tried running a `helm repo update`?

**Comment by consideRatio** [comment]
I close this as stale as it received no followup.
