### ISSUE TITLE
Link this repo on the website?

### ISSUE THREAD

**Issue by kazimuth** [dask/helm-chart#57]
The "source" link on the website goes to dask/dask, not this repo.

**Comment by jacobtomlinson** [comment]
Thanks for raising this. Which link are you referring to? Could you point me to it?

**Comment by kazimuth** [comment]
At https://helm.dask.org/ , the link labeled "Source" :)

**Comment by jacobtomlinson** [comment]
> link on the website 

Sorry, we have lots of websites, didn't know which you were referring to.

I feel like this is expected behaviour. The source link goes to the source of Dask.

Are you expecting it to go to the source of the chart?

**Comment by kazimuth** [comment]
Yes, because it's the website specifically for this chart and not for the larger Dask project? That there's no link to the chart source code (this repo) on the chart website (https://helm.dask.org/)
is surprising to me.

**Comment by jacobtomlinson** [comment]
Perhaps adding a GitHub corner link to that page would make sense?

http://tholman.com/github-corners/

**Comment by jacobtomlinson** [comment]
This has now been done.
