### ISSUE TITLE
Helm Chart freezes

### ISSUE THREAD

**Issue by kyprifog** [dask/helm-chart#58]
Using the default set up the helm chart is freezing for me:

```
helm install --wait dask --name dask --debug
[debug] Created tunnel using local port: '61002'

[debug] SERVER: "127.0.0.1:61002"

[debug] Original chart version: ""
[debug] CHART PATH: charts/dask
```

It freezes after this point.  If I kill it everything looks good except the LoadBalancers.   
Changing LoadBalancer to NodePort or ClusterIP solves the issue but then obviously I dont have the external IP which I need.  I assume this means that the LoadBalancers are not able to deploy.

I've tried added permissions for AWS ELB to no avail to solve the issue.  It might be worth adding some documentation for LoadBalancer deployments on AWS if there is anything unique about the dask chart in how it approaches it.

**Comment by jacobtomlinson** [comment]
This will be because of your `--wait` option. It is waiting for the load balancers to provision.

The Dask chart just creates two load balancers, one for the scheduler and one for the notebook. 

I'm afraid this sounds like an issue with your cluster setup and so we won't be able to provide assistance.

**Comment by kyprifog** [comment]
Answering my own question, I found an error in k8s related to missing role:
``` 
iam:CreateServiceLinkedRole
```

which was not included in the sample policies i was working from.  I had added all the permissions for ELB but not this one.

**Comment by jacobtomlinson** [comment]
Coming back to update us on your solution is much appreciated. Thanks @kyprifog.
