### ISSUE TITLE
Does it make sense to have workers on the same node?

### ISSUE THREAD

**Issue by JulianWgs** [dask/helm-chart#81]
Hello,

I don't if this is a feature request or bug. Feel free to change it.

Sometimes it happens that kubernetes schedules workers on the same node, but leaves out others. I would like to know if it makes sense to schedule workers on the same node? Wouldn`t they just steal each others ressources?

If so I would like to propose to add a default affinity to the workers similar to this:

```json
{
   "podAntiAffinity":{
      "requiredDuringSchedulingIgnoredDuringExecution":[
         {
            "topologyKey":"kubernetes.io/hostname",
            "labelSelector":{
               "matchLabels":{
                  "app":"dask",
                  "component":"worker"
               }
            }
         }
      ]
   }
}
```

**Comment by jacobtomlinson** [comment]
It shouldn't really matter. You should be explicit about the amount of resource that each worker gets by setting the `resources` configuration.

https://github.com/dask/helm-chart/blob/288ce3ca11f06cf9de98acdcb6baeb24eb3035ce/dask/values.yaml#L65-L73

Then no worker will steal resources from another and Kubernetes can schedule work however it sees fit.

**Comment by JulianWgs** [comment]
My question is still unanswered: Does it make sense to do it? Is there a use case when I want to do that? 

Say if I want 10 workers I don't expect them to be all on the same node.

Greetings,
Julian

**Comment by jacobtomlinson** [comment]
If all 10 workers fit on the node (i.e the node is at least 10x larger than the requested resources of each worker) then there is no problem with kubernetes doing that. They will all get their fair share of resources.

**Comment by JulianWgs** [comment]
Okay, then. Thanks for the clarification!
