### ISSUE TITLE
Unable to access loadbalancer url with installation on AWS

### ISSUE THREAD

**Issue by jsanjay63** [dask/helm-chart#90]
I tried deploying on AWS using helm charts using the command below:
`helm install dask dask/dask --set scheduler.serviceType=LoadBalancer --set jupyter.serviceType=LoadBalancer`

mentioned as part of https://docs.dask.org/en/latest/setup/kubernetes-helm.html

**What happened**:
Able to get the External URL for dask-jupyter by executing the command: `kubectl get svc`
But, I am unable to access this URL from my machine.

**What you expected to happen**:
Loadbalancer URL should be public and accessible

**Environment**:

- Dask version:
- Python version:
- Operating System: Windows
- Install method (conda, pip, source):

**Comment by jacobtomlinson** [comment]
Could you please share information on how you set up your Kubernets cluster and what the output of `kubectl get svc` was.

**Comment by jsanjay63** [comment]
Got this resolved..issue was with my cluster setup. Thanks 👍
